spring:
  application: "SSBlockchain Core"
  profiles:
    active: "live"
server:
  port: 9000
blockchain:
  hot-blocks: 20
  p2p:
    node-name: "blockchain-core-node"
    port: 9090
    active-connections: 10
    timeout: 30